vlog -work work C:/Users/Kauan/Documents/OAC/simulation/modelsim/teste.vwf.vt
vsim -novopt -c -t 1ps -L cycloneii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.test_vlg_vec_tst
onerror {resume}
add wave {test_vlg_vec_tst/i1/CLOCK}
add wave {test_vlg_vec_tst/i1/INSTRUCAO}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[31]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[30]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[29]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[28]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[27]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[26]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[25]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[24]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[23]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[22]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[21]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[20]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[19]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[18]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[17]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[16]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[15]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[14]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[13]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[12]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[11]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[10]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[9]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[8]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[7]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[6]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[5]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[4]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[3]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[2]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[1]}
add wave {test_vlg_vec_tst/i1/INSTRUCAO[0]}
add wave {test_vlg_vec_tst/i1/PC}
add wave {test_vlg_vec_tst/i1/PC[31]}
add wave {test_vlg_vec_tst/i1/PC[30]}
add wave {test_vlg_vec_tst/i1/PC[29]}
add wave {test_vlg_vec_tst/i1/PC[28]}
add wave {test_vlg_vec_tst/i1/PC[27]}
add wave {test_vlg_vec_tst/i1/PC[26]}
add wave {test_vlg_vec_tst/i1/PC[25]}
add wave {test_vlg_vec_tst/i1/PC[24]}
add wave {test_vlg_vec_tst/i1/PC[23]}
add wave {test_vlg_vec_tst/i1/PC[22]}
add wave {test_vlg_vec_tst/i1/PC[21]}
add wave {test_vlg_vec_tst/i1/PC[20]}
add wave {test_vlg_vec_tst/i1/PC[19]}
add wave {test_vlg_vec_tst/i1/PC[18]}
add wave {test_vlg_vec_tst/i1/PC[17]}
add wave {test_vlg_vec_tst/i1/PC[16]}
add wave {test_vlg_vec_tst/i1/PC[15]}
add wave {test_vlg_vec_tst/i1/PC[14]}
add wave {test_vlg_vec_tst/i1/PC[13]}
add wave {test_vlg_vec_tst/i1/PC[12]}
add wave {test_vlg_vec_tst/i1/PC[11]}
add wave {test_vlg_vec_tst/i1/PC[10]}
add wave {test_vlg_vec_tst/i1/PC[9]}
add wave {test_vlg_vec_tst/i1/PC[8]}
add wave {test_vlg_vec_tst/i1/PC[7]}
add wave {test_vlg_vec_tst/i1/PC[6]}
add wave {test_vlg_vec_tst/i1/PC[5]}
add wave {test_vlg_vec_tst/i1/PC[4]}
add wave {test_vlg_vec_tst/i1/PC[3]}
add wave {test_vlg_vec_tst/i1/PC[2]}
add wave {test_vlg_vec_tst/i1/PC[1]}
add wave {test_vlg_vec_tst/i1/PC[0]}
run -all
